pipeline {
            agent any
        
            options {
                gitLabConnection('gitlab')
            }
        
            stages {
                stage("build") {
                    agent { 
                        docker { 
                            image 'python:3.6'
                            args '-u root'
                        }
                    }
                    steps {
                        sh """
                        pip3 install --user virtualenv
                        python3 -m virtualenv env
                        . env/bin/activate
                        pip3 install -r requirements.txt
                        python3 manage.py check
                        """
                    }
                }
                stage("test") {
                    agent { 
                        docker { 
                            image 'python:3.6'
                            args '-u root'
                        }
                    }
                    steps {
                        sh """
                        pip3 install --user virtualenv
                        python3 -m virtualenv env
                        . env/bin/activate
                        pip3 install -r requirements.txt
                        python3 manage.py test taskManager
                        """
                    }
                }
                stage("integration") {
                    steps {
                        catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                            echo "This is an integration step"
                            sh "exit 1"
                        }
                    }
                }
                stage("prod") {
                    steps {
                        input "Deploy artefact to production?"
                        echo "This is a deploy step"
                    }
                }
                stage("artifact") {
                    steps {
                        script {
                            // Create a simple text file using the echo command
                            sh 'echo "This is an artefact file" > artefact.txt'
        
                            // Archive the artifact file
                            archiveArtifacts artifacts: 'artefact.txt'
                        }
                    }
                }
                stage("release"){
                environment {
                    registryUrl = "gitlab-registry-test.training"
                    registryCreds = "registry-auth" // Jenkins Credentials Id to authenticate with Docker Registry
                }
                steps{
                    script {
                        dockerImage = docker.build registryUrl + "/root/django-nv:$BUILD_NUMBER"
                        docker.withRegistry('https://' + registryUrl, registryCreds) {   
                            dockerImage.push()
                        }
                    }
                }
          
            post {
                failure {
                    updateGitlabCommitStatus(name: "\${env.STAGE_NAME}", state: 'failed')
                }
                unstable {
                    updateGitlabCommitStatus(name: "\${env.STAGE_NAME}", state: 'failed')
                }
                success {
                    updateGitlabCommitStatus(name: "\${env.STAGE_NAME}", state: 'success')
                }
                aborted {
                    updateGitlabCommitStatus(name: "\${env.STAGE_NAME}", state: 'canceled')
                }
                always { 
                    deleteDir()            // clean up workspace
                }
            }
        }
    }    
}
